In [1]:
import numpy


In [2]:
#array creation from a list - in this case a 2x2 matrix is built up from a "list of lists"
my_test_array = numpy.array([[3,2,4],[4,8,6],[2,0,5]])

In [3]:
my_test_array

array([[3, 2, 4],
       [4, 8, 6],
       [2, 0, 5]])

In [10]:
#we can ask what the dimension of the array is


In [11]:
my_test_array.shape

(3, 3)

In [12]:
3 in my_test_array


True

In [13]:
[4,8,6] in my_test_array

True

In [14]:
[4,8,3] in my_test_array

True

In [15]:
#:-( if any number of the testing list exists in the array "in" returns true.... 

In [16]:
type(my_test_array)

numpy.ndarray

In [18]:
my_test_array.dtype

dtype('int64')

In [21]:
#create a matrix filled with ones - takes as argument a list with two numbers - rows and columns
numpy.ones([6,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
#create a matrix filled with zeroes - takes as argument a list with two numbers - rows and columns
numpy.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
#create an identity array - as an identity matrix must be an square matrix only argument it take is number of rows == columns
numpy.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
#multiplying matrix
arr1 = numpy.array([[3,2,1],[2,4,5]])
arr2 = numpy.array([[4,2],[3,2],[1,1]])
arrresult = numpy.matmul(arr1,arr2)
arrresult


array([[19, 11],
       [25, 17]])

In [32]:
arr1.shape

(2, 3)

In [33]:
arr2.shape

(3, 2)

In [59]:
#use of slice notation

#original array

originalArray = numpy.matrix([[2,3,4],[4,5,6],[7,8,9]])

#sliced array all the rows but only first two columns
slicedArray = originalArray[:,:2]

In [60]:
slicedArray

matrix([[2, 3],
        [4, 5],
        [7, 8]])

In [67]:
# refering to a specific row
slicedArray[2,:]

matrix([[7, 8]])

In [68]:
#refering to a specific column
slicedArray[:,0]

matrix([[2],
        [4],
        [7]])

In [3]:
import numpy
#matrix trasposition
my_matrix = numpy.matrix(range(1,200,2))

In [4]:
my_matrix

matrix([[  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
          27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
          53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
          79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
         105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
         131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
         157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
         183, 185, 187, 189, 191, 193, 195, 197, 199]])

In [5]:
my_matrix.reshape(10,10)

matrix([[  1,   3,   5,   7,   9,  11,  13,  15,  17,  19],
        [ 21,  23,  25,  27,  29,  31,  33,  35,  37,  39],
        [ 41,  43,  45,  47,  49,  51,  53,  55,  57,  59],
        [ 61,  63,  65,  67,  69,  71,  73,  75,  77,  79],
        [ 81,  83,  85,  87,  89,  91,  93,  95,  97,  99],
        [101, 103, 105, 107, 109, 111, 113, 115, 117, 119],
        [121, 123, 125, 127, 129, 131, 133, 135, 137, 139],
        [141, 143, 145, 147, 149, 151, 153, 155, 157, 159],
        [161, 163, 165, 167, 169, 171, 173, 175, 177, 179],
        [181, 183, 185, 187, 189, 191, 193, 195, 197, 199]])

In [6]:
my_matrix

matrix([[  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
          27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
          53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
          79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
         105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
         131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
         157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
         183, 185, 187, 189, 191, 193, 195, 197, 199]])

In [12]:
my_matrix

matrix([[  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
          27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
          53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
          79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
         105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
         131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
         157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
         183, 185, 187, 189, 191, 193, 195, 197, 199]])

In [13]:
my_matrix.T

matrix([[  1],
        [  3],
        [  5],
        [  7],
        [  9],
        [ 11],
        [ 13],
        [ 15],
        [ 17],
        [ 19],
        [ 21],
        [ 23],
        [ 25],
        [ 27],
        [ 29],
        [ 31],
        [ 33],
        [ 35],
        [ 37],
        [ 39],
        [ 41],
        [ 43],
        [ 45],
        [ 47],
        [ 49],
        [ 51],
        [ 53],
        [ 55],
        [ 57],
        [ 59],
        [ 61],
        [ 63],
        [ 65],
        [ 67],
        [ 69],
        [ 71],
        [ 73],
        [ 75],
        [ 77],
        [ 79],
        [ 81],
        [ 83],
        [ 85],
        [ 87],
        [ 89],
        [ 91],
        [ 93],
        [ 95],
        [ 97],
        [ 99],
        [101],
        [103],
        [105],
        [107],
        [109],
        [111],
        [113],
        [115],
        [117],
        [119],
        [121],
        [123],
        [125],
        [127],
        [129],
        [131],
        [1

In [18]:
#universal functions
import numpy as np

test_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
test_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.log(test_array)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])